#ifndef __EYRIE_CALL_H__
#define __EYRIE_CALL_H__

#define RUNTIME_SYSCALL_UNKNOWN             1000
#define RUNTIME_SYSCALL_OCALL               1001
#define RUNTIME_SYSCALL_SHAREDCOPY          1002
#define RUNTIME_SYSCALL_ATTEST_ENCLAVE      1003
#define RUNTIME_SYSCALL_GET_SEALING_KEY     1004
#define RUNTIME_SYSCALL_MAP_SHM             1005
#define RUNTIME_SYSCALL_UNMAP_SHM           1006
#define RUNTIME_SYSCALL_MYDEV_MAP 	    1007
#define RUNTIME_SYSCALL_MYDEV_UNMAP         1008
#define RUNTIME_SYSCALL_EXIT                1101

#endif  // __EYRIE_CALL_H__
